export const translate = {
  grass: "Grama",
  poison: "Venenoso",
  fire: "Fogo",
  flying: "Voador",
  water: "Agua",
  bug: "Inseto",
  normal: "Normal",
  electric: "Eletrico",
  ground: "Terra",
  fairy: "Fada",
  fighting: "Lutador",
  psychic: "Psiquico",
  rock: "Pedra",
  steel: "Aço",
  ice: "Gelo",
  ghost: "Fantasma",
};
